package com.lasttrain.registry;

import com.lasttrain.LastTrain;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.sounds.SoundEvent;

/** Sounds from assets/lasttrain/sounds.json (generated by tools/gen_sounds.py). */
public final class ModSounds {
	public static final SoundEvent DRONE = register("ambient.drone");
	public static final SoundEvent CLOCK = register("ambient.clock");
	public static final SoundEvent LULLABY = register("ambient.lullaby");
	public static final SoundEvent WHISPER = register("ambient.whisper");
	public static final SoundEvent STATIC = register("ambient.static");
	public static final SoundEvent CREAK = register("block.creak");
	public static final SoundEvent GIGGLE = register("entity.doll.giggle");
	public static final SoundEvent CLICK = register("item.flashlight.click");
	public static final SoundEvent REWIND = register("ui.rewind");
	public static final SoundEvent DOPPEL_SCREAM = register("entity.doppelganger.scream");
	// the Blind One: its own voice, nothing borrowed from the Warden
	public static final SoundEvent BLIND_BREATHE = register("entity.blind_one.breathe");
	public static final SoundEvent BLIND_CLICK = register("entity.blind_one.click");
	public static final SoundEvent BLIND_SNARL = register("entity.blind_one.snarl");
	public static final SoundEvent BLIND_SCREAM = register("entity.blind_one.scream");
	public static final SoundEvent BLIND_ATTACK = register("entity.blind_one.attack");
	public static final SoundEvent BLIND_STEP = register("entity.blind_one.step");
	/** Your own heart when it is close. */
	public static final SoundEvent HEARTBEAT = register("ambient.heartbeat");

	private ModSounds() {
	}

	private static SoundEvent register(String name) {
		return Registry.register(BuiltInRegistries.SOUND_EVENT, LastTrain.id(name), SoundEvent.createVariableRangeEvent(LastTrain.id(name)));
	}

	public static void init() {
	}
}
